/**
 * Recommendation types.
 *
 * Recommendations are generated by the RecommendationEngine after evaluation.
 * They are suggestions — not constraints — and carry a priority and reasoning
 * string designed for both human review and LLM prompt construction.
 */

export type RecommendationKind =
  | "UPSELL"                    // suggest adding a compatible accessory/upgrade
  | "PROFITABILITY_IMPROVEMENT" // raise price or swap to higher-margin variant
  | "FREIGHT_CONSOLIDATION"     // merge freight lines for saving
  | "ALTERNATIVE_VARIANT"       // swap to a functionally-equivalent but cheaper/better variant
  | "WARNING_ALERT"             // surface a risk or compliance issue
  | "BUNDLE_OPPORTUNITY"        // suggest bundling for commercial advantage
  | "LEAD_TIME_ALERT";          // flag critical-path lead-time risk

export type RecommendationPriority = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";

export interface QuoteRecommendation {
  id: string;
  kind: RecommendationKind;
  priority: RecommendationPriority;
  title: string;
  /** Human-readable reasoning (also used as LLM context). */
  reasoning: string;

  // ── Context ───────────────────────────────────────────────────────────────
  /** Node(s) this recommendation addresses. */
  targetNodeIds: string[];
  /** Estimated financial impact of acting on this recommendation. */
  estimatedImpact?: {
    revenueChange?: number;
    marginChange?: number;
    marginPctChange?: number;
    currency: string;
  };
  /** Suggested action payload (used by AI agents to auto-apply). */
  actionPayload?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}
